if(EXISTS "/home/guillaume/Documents/LIRMM/project/rappas-recomb/release-build/core/tests/tests_n_tests-b858cb2.cmake")
  include("/home/guillaume/Documents/LIRMM/project/rappas-recomb/release-build/core/tests/tests_n_tests-b858cb2.cmake")
else()
  add_test(tests_n_NOT_BUILT-b858cb2 tests_n_NOT_BUILT-b858cb2)
endif()
