language: cpp

# see https://github.com/nlohmann/json/blob/develop/.travis.yml
matrix:
  # standard g++-8 build
  include:
  - os: linux
    compiler: gcc
    env:
    - COMPILER=g++-8
    - CXXFLAGS="-Wno-unknown-pragmas -O2"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8']

  # 32bit build
  - os: linux
    compiler: gcc
    env:
    - COMPILER=g++-8
    - CXXFLAGS="-Wno-unknown-pragmas -O2 -m32"
    - LDFLAGS="-m32"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8-multilib', 'linux-libc-dev:i386']        

  # build for c++17
  - os: linux
    compiler: gcc
    env:
    - COMPILER=g++-8
    - CXXFLAGS="-Wno-unknown-pragmas -O2 -std=c++17"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8']

  # -fsanitize=undefined
  - os: linux
    compiler: gcc
    env:
    - COMPILER=g++-8
    - CXXFLAGS="-Wno-unknown-pragmas -O2 -fsanitize=undefined"
    - LDFLAGS="-fuse-ld=gold -fsanitize=undefined"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8']

  # -fsanitize=address with additional checks
  - os: linux
    compiler: gcc
    env:
    - COMPILER=g++-8
    - CXXFLAGS="-Wno-unknown-pragmas -O2 -fsanitize=pointer-compare -fsanitize=pointer-subtract -fsanitize=address"
    - LDFLAGS="-fuse-ld=gold -fsanitize=pointer-compare -fsanitize=pointer-subtract -fsanitize=address"
    - ASAN_OPTIONS=verbosity=1:detect_invalid_pointer_pairs=2
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8']

  # clang should work too
  - os: linux
    compiler: clang
    env:
    - COMPILER=clang++-6.0
    - CXXFLAGS="-Wno-unknown-pragmas -O2"
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['g++-6', 'clang-6.0',]

script:
  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # show OS/compiler version
  - uname -a
  - $CXX --version

  # build
  - make -j4 all

  # check file
  - file ./build/robinhood-test

  # run test
  - ./build/robinhood-test